### PR TITLE
Refactor for stackdriver agent logging v2

### PR DESCRIPTION
**Pull request by balboah**

### CODE REVIEW

**Comment by andpol** [comment]
Oh, this is just perfect timing @balboah! I was just yesterday looking at adding this to our project and finding issues with the format. I've only skimmed the code, but it looks promising so far! Thanks for making this module public :smiley:

**Comment by balboah** [comment]
@andpol thanks for reaching out :) I haven't needed this myself for a while, but now I couldn't find anything that seemed updated so lets make this work.

Keep in mind I've only tested that basic logging and part of http request works on Cloud Run so far.

**Comment by balboah** [comment]
can confirm it works well with latest google stackdriver agent fluentd. Haven't tested httpRequest that much tho

**Comment by andpol** [comment]
We're also not doing a ton more than the basics. I can also confirm that latest changes work well with the Google Stackdriver agent (fluentd), in our case with GKE version `1.13.5-gke.10`.

**Pull request merged**
